
### GEOMETRY

/Geometry/FullRingLYSO/depth 3. cm
/Geometry/FullRingLYSO/pitch 7. mm
/Geometry/FullRingLYSO/inner_radius 380. mm
/Geometry/FullRingLYSO/sipm_rows 278
/Geometry/FullRingLYSO/instrumented_faces 1
/Geometry/FullRingLYSO/cryostat_width 200 cm
/Geometry/FullRingLYSO/specific_vertex_X 0. mm
/Geometry/FullRingLYSO/specific_vertex_Y 390. mm
/Geometry/FullRingLYSO/specific_vertex_Z 0. mm

#/Geometry/FullRingLYSO/pointFile /home/jrenner/production/petalo/phantoms/phantom_cylinder.dat

/Geometry/SiPMpet/efficiency 0.2
/Geometry/SiPMpet/visibility true
/Geometry/SiPMpet/time_binning 1. microsecond
/Geometry/SiPMpet/size 6. mm
/Geometry/SiPMpet/refr_index 1.54


### GENERATOR
#/Generator/Back2back/region CENTER
/Generator/SingleParticle/region AD_HOC
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 511 keV
/Generator/SingleParticle/max_energy 511 keV

#/Actions/DefaultEventAction/energy_threshold .511 MeV

/PhysicsList/Nexus/nest false
/PhysicsList/Nexus/scintRiseTime true

### VERBOSITIES
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/nexus/random_seed 132312

### OUTPUT FILE

/nexus/persistency/start_id 0
/nexus/persistency/sns_only false
/nexus/persistency/tof_time 50. nanosecond
/nexus/persistency/outputFile full_body_lyso.pet
