
### GEOMETRY

/Geometry/FullRingInfinity/depth 3. cm
/Geometry/FullRingInfinity/pitch 7. mm
/Geometry/FullRingInfinity/inner_radius 3800. mm
/Geometry/FullRingInfinity/sipm_rows 278
/Geometry/FullRingInfinity/instrumented_faces 1
/Geometry/FullRingInfinity/cryostat_width 200 cm

#/Geometry/FullRingInfinity/pointFile /home/jrenner/production/petalo/phantoms/phantom_cylinder.dat

/Geometry/SiPMpet/efficiency 0.3
/Geometry/SiPMpet/visibility true
/Geometry/SiPMpet/time_binning 1. microsecond
/Geometry/SiPMpet/size 6. mm
/Geometry/SiPMpet/refr_index 1.6


### GENERATOR

/Generator/ScintGenerator/nphotons 30000
/Generator/ScintGenerator/region ACTIVE

### VERBOSITIES
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/nexus/random_seed 132312

### OUTPUT FILE

/nexus/persistency/start_id 0
/nexus/persistency/sns_only false
/nexus/persistency/tof_time 5. nanosecond
/nexus/persistency/outputFile test_wndw_n1.6_box_plane
