### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

### GEOMETRY
/Geometry/RegisterGeometry FULLRING

### GENERATOR
/Generator/RegisterGenerator SCINTILLATION

### ACTIONS
/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction EL_SIM
/Actions/RegisterTrackingAction OPTICAL

/nexus/RegisterMacro test_windows.config.mac
