### --------------------------------------------------------
###  Next100: Configuration macro
###  $Id: Next100.Neutron.config.mac 8758 2016-11-09 15:12:45Z minegui $
### --------------------------------------------------------







##### GEOMETRY #####


##### GENERATOR #####

# Region options: EXTERNAL, SHIELDING_LEAD, SHIELDING_STEEL, SHIELDING_GAS, SHIELDING_STRUCT
#                 VESSEL, VESSEL_FLANGES, VESSEL_TRACKING_ENDCAP, VESSEL_ENERGY_ENDCAP
#		  ICS, DB_PLUG,
#		  FIELD_CAGE, ACTIVE, CARRIER_PLATE, ENCLOSURE, ENCLOSURE_WINDOW, ENCLOSURE_PAD,
#		  PMT_BODY, PMT, TRK_SUPPORT, DICE_BOARD, EL_TABLE

# Single Particle
/Generator/SingleParticle/particle p
/Generator/SingleParticle/min_energy 2 GeV
/Generator/SingleParticle/max_energy 2 GeV
/Generator/SingleParticle/region BEAM
/Generator/SingleParticle/momentum_direction (0, -1, 0)



##### VERBOSITIES #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


##### JOB CONTROL #####
/nexus/persistency/hdf5 true
/nexus/persistency/outputFile cevns_test