## ----------------------------------------------------------------------------
## nexus | NEXT100_full.config.mac
##
## Configuration macro to simulate Kr-83 decays in the NEXT-100 geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield true
/Geometry/Next100/EL_field 3 kV/cm
/Geometry/Next100/pressure 1. bar
/Geometry/Next100/max_step_size 1. mm
#/Geometry/Next100/use_dielectric_grid true

/Geometry/Next100/photoe_prob 1.e-3
/process/optical/processActivation Cerenkov false

##### GENERATOR #####
/Generator/Kr83mGenerator/region ACTIVE

/PhysicsList/Nexus/photoelectric true

##### PERSISTENCY #####
/nexus/persistency/output_file Next100_full.next
