### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

### GEOMETRY
/Geometry/RegisterGeometry FULLRING

### GENERATOR
#/Generator/RegisterGenerator BACK2BACK
/Generator/RegisterGenerator SINGLE_PARTICLE

### ACTIONS
/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterTrackingAction DEFAULT
#/Actions/RegisterStackingAction NEST

/nexus/RegisterMacro macros/PET_full_body_test.config.mac
